[tool.poetry]
name = "milarun"
version = "0.1.0"
description = "Benchmarking suite for machine learning algorithms"
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
giving = "^0.3.6"
ptera = "^0.5.1"
rich = "^10.13.0"
coleo = "^0.2.6"
requests = "^2.26.0"
nox = "^2021.10.1"
GitPython = "^3.1.24"
PyYAML = "^6.0"
ovld = "^0.3.2"
GPUtil = "^1.4.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
milarun = "milarun.cli:main"

[tool.isort]
known_first_party = "ptera"
known_third_party = "numpy,torch,torchvision"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
