[tool.poetry]
name = "milabench"
version = "0.1.0"
description = "Benchmarking suite for machine learning algorithms"
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
giving = "^0.3.7"
ptera = "^1.0.1"
rich = "^10.13.0"
coleo = "^0.3.0"
requests = "^2.26.0"
nox = "^2021.10.1"
GitPython = "^3.1.24"
PyYAML = "^6.0"
ovld = "^0.3.2"
GPUtil = "^1.4.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
milabench = "milabench.cli:main"

[tool.poetry.plugins."voir.instrument"]
profile_gpu = "milabench.instruments:profile_gpu"
display = "milabench.instruments:display"
stop = "milabench.instruments:stop"
rates = "milabench.instruments:rates"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
