defaults: &defaults
  dirs:
    code: ./_dev_{name}
    venv: venv/{name}
    data: data
    runs: runs

  venv:
    type: virtualenv

  plan:
    method: njobs
    n: 1

  pip:
    args:
      - --extra-index-url https://download.pytorch.org/whl/cu111
    constraints:
      - torch==1.10.2+cu111
      - torchvision==0.11.3+cu111
      - torchtext==0.11.*

  voir:
    --stop: 10
    --forward:
      - "#stdout"
      - "#stderr"
      - "#end"
      - loss
      - compute_rate
      - train_rate
      - loading_rate
      - descr
      - progress
      - total
    --compute-rate: true
    --train-rate: true
    --loading-rate: true

benchmarks:
  torchbench:
    <<<: *defaults

    definition: ./
