from: "./base.yaml"

benchmarks:
  resnet50-fp16:
    argv:
      --model: resnet50
      --batch-size: $(bs(gpu, mem, default=512))
      --with-amp: True

  resnet50-fp32:
    argv:
      --model: resnet50
      --batch-size: $(bs(gpu, mem, default=256))
      --with-amp: null
  
  efficientnet_b4:
    argv:
      --model: efficientnet_b4
      --batch-size: $(bs(gpu, mem, default=256))

  efficientnet_b7:
    argv:
      --model: efficientnet_b7
      --batch-size: $(bs(gpu, mem, default=64))
    
  convnext_large:
    argv:
      --model: convnext_large
      --batch-size: $(bs(gpu, mem, default=64))
  
  regnet_y_128gf:
    argv:
      --model: regnet_y_128gf
      --batch-size: $(bs(gpu, mem, default=32))
      --with-amp: null
 
  bert:
    argv:
      --model: "Bert"
      --batch-size: $(bs(gpu, mem, default=16))

  t5:
    argv:
      --model: "T5"
      --batch-size: $(bs(gpu, mem, default=16))

  reformer:
    argv:
      --model: "Reformer"
      --batch-size: $(bs(gpu, mem, default=16))
  
  resnet152:
    argv:
      --backbone: "resnet152"
      --strategy: "ddp"
      --precision: 32
      --batch_size: $(bs(gpu, mem, default=12, multi_gpu=True))

  accelerate:
    # This is for single-node
    manager_addr: "127.0.0.1"
    manager_port: 10000

    num_processes: 2
    cpus_per_gpu: 8

    model_name: "facebook/bart-base"

    gradient_accumulation_steps: 1
    per_gpu_batch_size: 1
    max_train_steps: 5

    dataset_name: "wikitext"
    dataset_config_name: "wikitext-103-v1"
    validation_split_percentage: 5
