include:
  - base.yaml

resnet152:
  enabled: false

regnet_y_128gf:
  enabled: false

resnet152-ddp:
  enabled: false

resnet152-multi:
  enabled: false

stargan:
  enabled: false

resnet50:
  enabled: false

resnet50-noio:
  enabled: false

_resnet50:
  inherits: resnet50
  enabled: true
  argv:
    --iobench: true

# # bs: [32-512]
resnet50-bs32-w8:
  inherits: _resnet50

  argv:
    --batch-size: 32
    --num-workers: 8

resnet50-bs64-w8:
  inherits: _resnet50

  argv:
    --batch-size: 64
    --num-workers: 8

resnet50-bs128-w8:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 8

resnet50-bs256-w8:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 8

resnet50-bs512-w8:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 8


# #
# # w: [2-96]
# #
resnet50-bs256-w2:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 2

resnet50-bs256-w4:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 4

resnet50-bs256-w16:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 16

resnet50-bs256-w32:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 32

resnet50-bs256-w64:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 64


# #
# # NO IO
# #
resnet50-bs32-noio:
  inherits: _resnet50

  argv:
    --batch-size: 32
    --num-workers: 1
    --synthetic-data: true

resnet50-bs64-noio:
  inherits: _resnet50

  argv:
    --batch-size: 64
    --num-workers: 1
    --synthetic-data: true

resnet50-bs128-noio:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 1
    --synthetic-data: true

resnet50-bs256-noio:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 1
    --synthetic-data: true

resnet50-bs512-noio:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 1
    --synthetic-data: true


#
# Additional Run
#


resnet50-bs512-w16:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 16


resnet50-bs512-w32:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 32

resnet50-bs512-w4:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 4

resnet50-bs128-w16:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 16

resnet50-bs128-w32:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 32

resnet50-bs128-w4:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 4




resnet50-bs1024-w16:
  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 16

resnet50-bs1024-w32:
  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 32

resnet50-bs1024-w4:
  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 4

resnet50-bs1024-w8:
  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 8

resnet50-bs1024-noio:

  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 1
    --synthetic-data: true

#
# Use ALL CPUs
#

resnet50-bs32-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 32
    --num-workers: 24

resnet50-bs64-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 64
    --num-workers: 24

resnet50-bs128-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 128
    --num-workers: 24

resnet50-bs256-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 256
    --num-workers: 24

resnet50-bs512-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 512
    --num-workers: 24

resnet50-bs1024-w24:
  inherits: _resnet50
  
  argv:
    --batch-size: 1024
    --num-workers: 24
